-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cita"
(
    id_cita integer NOT NULL,
    "fechaHora_cita" timestamp without time zone NOT NULL,
    id_cliente integer NOT NULL,
    id_gym integer NOT NULL,
    CONSTRAINT "Cita_pkey" PRIMARY KEY (id_cita)
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    id_cliente integer NOT NULL,
    nombre_cliente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos_cliente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email_cliente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fnac_cliente date,
    id_ejercicio integer NOT NULL,
    CONSTRAINT "Cliente_pkey" PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public."Ejercicio"
(
    id_ejercicio integer NOT NULL,
    nombre_ejercicio character varying COLLATE pg_catalog."default" NOT NULL,
    series integer NOT NULL,
    repeticiones integer NOT NULL,
    CONSTRAINT "Ejercicio_pkey" PRIMARY KEY (id_ejercicio)
);

CREATE TABLE IF NOT EXISTS public."Gimnasio"
(
    id_gym integer NOT NULL,
    nombre_gym character varying(500) COLLATE pg_catalog."default" NOT NULL,
    imagen_gym bytea,
    email_gym character varying COLLATE pg_catalog."default" NOT NULL,
    direccion_gym character varying(500) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(50) COLLATE pg_catalog."default",
    id_responsable integer,
    CONSTRAINT "Gimnasio_pkey" PRIMARY KEY (id_gym)
);

CREATE TABLE IF NOT EXISTS public."Responsable"
(
    id_responsable integer NOT NULL,
    nombre_responsable character varying(500) COLLATE pg_catalog."default" NOT NULL,
    apellidos_responsable character varying(500) COLLATE pg_catalog."default" NOT NULL,
    email_responsable character varying(500) COLLATE pg_catalog."default" NOT NULL,
    telefono_responsable character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Responsable_pkey" PRIMARY KEY (id_responsable)
);

ALTER TABLE IF EXISTS public."Cita"
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public."Cliente" (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cita"
    ADD CONSTRAINT id_gym FOREIGN KEY (id_gym)
    REFERENCES public."Gimnasio" (id_gym) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT id_ejercicio FOREIGN KEY (id_ejercicio)
    REFERENCES public."Ejercicio" (id_ejercicio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Gimnasio"
    ADD CONSTRAINT "FK_id_responsable" FOREIGN KEY (id_responsable)
    REFERENCES public."Responsable" (id_responsable) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;